enum MoviesTypes {
  GET_MOVIES = 'GET_MOVIES',
  GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS',
  GET_MOVIES_ERROR = 'GET_MOVIES_ERROR',

  //GET_GENRES
  GET_GENRES = 'GET_GENRES',
  GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS',
  GET_GENRES_ERROR = 'GET_GENRES_ERROR',

  // GET_NOW_PLAYING
  GET_NOW_PLAYING = 'GET_NOW_PLAYINGS',
  GET_NOW_PLAYING_SUCCESS = 'GET_NOW_PLAYINGS_SUCCESS',
  GET_NOW_PLAYING_ERROR = 'GET_NOW_PLAYING_SUCCESS',
}
export default MoviesTypes;
