enum MoviesTypes {
  GET_MOVIES = 'GET_MOVIES',
  GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS',
  GET_MOVIES_ERROR = 'GET_MOVIES_ERROR',
  //
  GET_GENRES = 'GET_GENRES',
  GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS',
  GET_GENRES_ERROR = 'GET_GENRES_ERROR',
}
export default MoviesTypes;
